#!/bin/sh

set -e
set -u

install -m 0700 -d tmp

if [ -d "${1:-}" ]; then
    rootdir=$1
else
    rootdir="${PWD}/$(mktemp -d tmp/convert.XXXXXXXX)"
fi

rundir="${PWD}/run.d"

export SVN2GIT_AUTHORS="${PWD}/tmp/munin.svn/authors"
export SVN2GIT_SVN_REPO=svn+ssh://munin-monitoring.org/svn/munin
export SVN2GIT_SVN_WORKDIR="${PWD}/tmp/munin.svn"
export SVN2GIT_ROOTDIR=$rootdir

echo ": munin svn2git session ; ${0} ${rootdir}"

( cd $rootdir && run-parts --verbose --exit-on-error ${rundir} )

# Update "munin" symlink to point to latest successful run.
rm -f munin
ln -s ${rootdir}/munin.svn2git munin
