#!/bin/sh

set -e
set -u
set -x

if [ -d "${1:-}" ]; then
    rootdir=$1
else
    rootdir="${PWD}/$(mktemp -d convert.XXXXXXXX)"
fi
bindir="${PWD}/bin"
rundir="${bindir}/run.d"
authors="${PWD}/tmp/munin.svn/authors"

test -f $authors
test -d $bindir

cd $rootdir

export SVN2GIT_AUTHORS=$authors
export SVN2GIT_REPO=svn+ssh://munin-monitoring.org/svn/munin

run-parts ${rundir}
