#!/bin/sh

set -e
set -u
set -x

if [ -d "${1:-}" ]; then
    rootdir=$1
else
    rootdir="${PWD}/$(mktemp -d convert.XXXXXXXX)"
fi
bindir="${PWD}/bin"
authors="${PWD}/authors"

test -f $authors
test -d $bindir

cd $rootdir

export SVN2GIT_AUTHORS=$authors

if [ ! -d munin.svn2git ]; then
    ${bindir}/import-munin
    ${bindir}/merge-tags-to-master
fi

if [ ! -d munin-people.svn2git ]; then
    sh -x ${bindir}/import-munin-people
fi

if [ ! -d munin-packaging-simple.svn2git ]; then
    ${bindir}/import-munin-packaging-simple
fi

${bindir}/pull-branches

# Missing: import-munin-packaging-other

