#!/bin/sh

set -u
set -e

rootdir=$(mktemp -d munin-packaging-squeeze.XXXXXX)

import_from_svn() {
    echo "### Running svn2git..."
    svn2git --authors="$SVN2GIT_AUTHORS" \
        svn://munin-monitoring.org/munin/branches/debian/squeeze
}

sanity_check() {
    echo "### Sanity check"
    test -d .git
}

echo "### Importing to $rootdir"
cd $rootdir && import_from_svn && sanity_check

echo "### Done: $rootdir"

cd ..
test -d munin-packaging-squeeze.svn2git && exit 1 || true
mv $rootdir munin-packaging-squeeze.svn2git
echo "### Done: munin-packaging-squeeze.svn2git"
