#!/bin/sh

set -e
set -u

pre_check() {
    command -v svn >/dev/null
}

post_check() {
    svn info "${SVN2GIT_SVN_WORKDIR}" > /dev/null
}

checkout() {
    if [ ! -d ${SVN2GIT_SVN_WORKDIR} ]; then
        svn co "${SVN2GIT_SVN_REPO}/trunk" "${SVN2GIT_SVN_WORKDIR}"
    fi
}

pre_check
checkout
post_check
