#!/bin/sh

set -u
set -e

# Imports munin trunk, branches and tags into munin.svn2git 

pre_check() {
    if post_check; then
        echo "Already done, skipping."
        exit 0
    fi
    test -d ${SVN2GIT_SVN_WORKDIR}
    test -f ${SVN2GIT_SVN_WORKDIR}/authors
}

post_check() {
    test -d munin.svn2git
}

import_from_svn() {
    echo "### Running svn2git..."
    svn2git --authors="$SVN2GIT_AUTHORS" \
        --exclude=^/branches/debian \
        --exclude=^/people \
        ${SVN2GIT_SVN_REPO}
}

sanity_check() {
    echo "### Sanity check"
    test -d .git
}

rename_and_recreate_master() {
    git branch -m master develop
    git symbolic-ref HEAD refs/heads/master
    rm .git/index
    git clean -fdx
}

run_conversion() {
    rootdir=$(mktemp -d munin.XXXXXX)
    cd $rootdir

    import_from_svn
    sanity_check
    rename_and_recreate_master

    cd ..
    test -d munin.svn2git && exit 1 || true
    mv $rootdir munin.svn2git
}

pre_check
run_conversion
post_check
