#!/bin/sh

set -u
set -e
set -x

rootdir=$(mktemp -d munin.XXXXXX)

import_from_svn() {
    echo "### Running svn2git..."
    svn2git --authors="$SVN2GIT_AUTHORS" \
        --exclude=^/branches/debian \
        --exclude=^/people \
        ${SVN2GIT_REPO}
}

sanity_check() {
    echo "### Sanity check"
    test -d .git
}

rename_and_recreate_master() {
    git branch -m master develop
    git symbolic-ref HEAD refs/heads/master
    rm .git/index
    git clean -fdx
}

echo "### Importing to $rootdir"

cd $rootdir
import_from_svn && sanity_check
rename_and_recreate_master
echo "### Done: $rootdir"

cd ..
test -d munin.svn2git && exit 1 || true
mv $rootdir munin.svn2git
echo "### Done: munin.svn2git"
