#!/bin/sh

set -u
set -e

# Imports munin trunk, branches and tags into munin.svn2git

pre_check() {
    if [ -d munin.svn2git ]; then
        echo "Already done, skipping."
        exit 0
    fi
    test -d ${SVN2GIT_SVN_WORKDIR}
    test -f ${SVN2GIT_SVN_WORKDIR}/authors
}

post_check() {
    test -d munin.svn2git
    (
        cd munin.svn2git
        git branch --list master | grep -qw master
    )
}

import_from_svn() {
    svn2git --authors="$SVN2GIT_AUTHORS" \
        --exclude=^/branches/debian \
        --exclude=^/people \
        ${SVN2GIT_SVN_REPO}
}

run_conversion() {
    rootdir=$(mktemp -d munin.XXXXXX)
    ( cd $rootdir && import_from_svn )
    mv $rootdir munin.svn2git
}

pre_check
run_conversion
post_check
