#!/bin/sh

set -u
set -e

pre_check() {
    if post_check; then
        echo "Already done, skipping."
        exit 0
    fi
}

post_check() {
    test -d munin-packaging-lenny.svn2git
    test -d munin-packaging-lenny.svn2git/.git
}

import_from_svn() {
    echo "### Running svn2git..."
    svn2git --authors="$SVN2GIT_AUTHORS" \
        ${SVN2GIT_SVN_REPO}/branches/debian/lenny
}

sanity_check() {
    echo "### Sanity check"
    test -d .git
}

import_lenny() {
    rootdir=$(mktemp -d munin-packaging-lenny.XXXXXX)

    echo "### Importing to $rootdir"
    cd $rootdir
    import_from_svn
    sanity_check
    echo "### Done: $rootdir"

    cd ..
    test -d munin-packaging-lenny.svn2git && exit 1 || true
    mv $rootdir munin-packaging-lenny.svn2git
    echo "### Done: munin-packaging-lenny.svn2git"
}

pre_check
import_lenny
post_check
