#!/bin/sh

set -u
set -e

pre_check() {
    if post_check; then
        echo "Already done, skipping..."
        exit 0
    fi
}
post_check() {
    test -d munin-packaging-squeeze.svn2git
}

import_from_svn() {
    echo "### Running svn2git..."
    svn2git --authors="$SVN2GIT_AUTHORS" \
        ${SVN2GIT_SVN_REPO}/branches/debian/squeeze
}

sanity_check() {
    echo "### Sanity check"
    test -d .git
}

import_packaging() {
    rootdir=$(mktemp -d munin-packaging-squeeze.XXXXXX)

    echo "### Importing to $rootdir"
    cd $rootdir && import_from_svn && sanity_check

    echo "### Done: $rootdir"

    cd ..
    test -d munin-packaging-squeeze.svn2git && exit 1 || true
    mv $rootdir munin-packaging-squeeze.svn2git
    echo "### Done: munin-packaging-squeeze.svn2git"
}


pre_check
import_packaging
post_check
