#!/bin/sh

set -u
set -e

rootdir=$(mktemp -d munin-packaging-experimental.XXXXXX)

import_from_svn() {
    echo "### Running svn2git..."
    svn2git --authors="$SVN2GIT_AUTHORS" \
        ${SVN2GIT_REPO}/branches/debian/experimental
}

sanity_check() {
    echo "### Sanity check"
    test -d .git
}

echo "### Importing to $rootdir"
cd $rootdir && import_from_svn && sanity_check

echo "### Done: $rootdir"

cd ..
test -d munin-packaging-experimental.svn2git && exit 1 || true
mv $rootdir munin-packaging-experimental.svn2git
echo "### Done: munin-packaging-experimental.svn2git"
