#!/bin/sh

set -e
set -u

pre_check() {
    if post_check; then
        echo "Already done, skipping."
        exit 0
    fi
    test -d munin.svn2git
}

post_check() {
    test -d munin.svn2git
    (
        cd munin.svn2git
        git remote | grep -qx people
        git remote | grep -qx packaging-simple
    )
}

add_packaging_simple() {
    if ( git remote | grep -qx packaging-simple ); then
        return 0
    fi
    git remote add packaging-simple ../munin-packaging-simple.svn2git
    git remote update

    branches="$(git branch -r | tr -d '*' | grep packaging-simple/packaging)"
    for branch in $branches; do
        git checkout -b ${branch#packaging-simple/} $branch
    done
}

add_people() {
    if ( git remote | grep -qx people ); then
        return 0
    fi
    git remote add people ../munin-people.svn2git
    git remote update

    branches="$(git branch -r | tr -d '*' | grep people/people)"
    for branch in $branches; do
        git checkout -b ${branch#people/} $branch
    done
}

pull_branches() {
    (
        cd munin.svn2git
        add_packaging_simple
        add_people
    )
}

pre_check
pull_branches

